Vagrant.configure("2") do |config|
  # Use Ubuntu 20.04 base image
  config.vm.box = "bento/ubuntu-20.04"

  # Forward HAProxy port
  config.vm.network "forwarded_port", guest: 80, host: 8083

  # Install Puppet
  config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppet.com/puppet7-release-focal.deb -O /tmp/puppet7-release-focal.deb
    sudo dpkg -i /tmp/puppet7-release-focal.deb
    sudo apt update
    sudo apt install puppet -y
  SHELL

  # Provision with Puppet
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "modules"
    puppet.options = "--verbose --debug"
  end
end
