Vagrant.configure("2") do |config|
  # Use Ubuntu 20.04 base image
  config.vm.box = "bento/ubuntu-20.04"

  # Forward HAProxy port
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Provision with Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
