Vagrant.configure("2") do |config|
  # Use Ubuntu 20.04 base image
  config.vm.box = "bento/ubuntu-20.04"

  # Forward HAProxy port
  config.vm.network "forwarded_port", guest: 80, host: 8082

  # Provision with Chef
  config.vm.provision "chef_solo" do |chef|
    chef.roles_path = "roles"
    chef.add_role("app")
    chef.arguments = '--chef-license accept'
  end
end
